BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ALTER COLUMN [whatsapp] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[User] ALTER COLUMN [biography] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[User] ALTER COLUMN [hierarchy] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_hierarchy_df] DEFAULT 'STUDENT' FOR [hierarchy];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
